[METEOR 3]: Removing Fibers from Mocha
Meteor-Community-Packages/meteor-mocha pull request #147
Opened 2023-02-16 18:04 UTC by Grubba27

As explained here: https://github.com/meteor/meteor/pull/12515 we have a few changes that needed to be done in mocha in order to work with Meteor 3

2023-09-23 17:58 UTC, StorytellerCZ commented
I will prepare a special release so this can be tested.

2023-09-23 19:04 UTC, Grubba27 commented
This is currently running our CI in the core. We have published a version to test it.

2023-09-24 07:09 UTC, StorytellerCZ requested changes

2023-09-24 07:09 UTC, StorytellerCZ commented on package/package.js
> +  version: '3.0.3-alpha300.11',
The version you have here makes no sense. I get the major version bump, but where do the 3 patch versions come from?
Just keep it like `3.0.0-alpha.11` and increment the alpha number.

2023-09-26 15:32 UTC, Grubba27 commented on package/package.js
> +  version: '3.0.3-alpha300.11',
I agree! Before merging, I will correct this one. I did not realize that this was wrong. Thanks for the ping

2024-01-03 08:41 UTC, jankapunkt approved these changes

2024-01-03 08:41 UTC, merged